name: Skaffold Build Action
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  version:
    default: '1.13.0'
    description: Set Skaffold version
    required: false
  container-structure-test-version:
    default: '1.8.6'
    description: Set Container Structure Test version
    required: false
  default-repo:
    default: ''
    description: Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
    required: false
  tag:
    default: 'latest'
    required: false
    description: The optional custom tag to use for images which overrides the current Tagger configuration
  build-image:
    default: ''
    description: Skaffold version
    required: false
  profile:
    default: ''
    description: Activate profiles by name (prefixed with `-` to disable a profile)
    required: false
  skip-tests:
    default: 'false'
    description: Whether to skip the tests after building
    required: false
  command:
    description: Skaffold command to execute
    required: true
outputs: {}
runs:
  using: node12
  main: dist/index.js
