name: Skaffold Setup
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  skaffold-version:
    description: Skaffold version
    required: false
    default: 1.9.0
outputs: {}
runs:
  using: docker
  image: Dockerfile
  args:
    - version
