name: Skaffold Build Action
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  default-repo:
    description: Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
    required: false
  tag:
    required: false
    description: The optional custom tag to use for images which overrides the current Tagger configuration
  build-image:
    description: Skaffold version
    required: false
  profile:
    description: Activate profiles by name (prefixed with `-` to disable a profile)
    required: false
  entrypoint:
    default: skaffold
    description: Default entrypoint
    required: false
  args:
    default: build
    required: false
    description: Command line arguments
  docker_username:
    description: Docker username
    required: false
  docker_password:
    description: Docker password
    required: false
  skip-tests:
    default: 'false'
    description: Whether to skip the tests after building
    required: false
outputs: {}
runs:
  using: docker
  image: Dockerfile
  env:
    DOCKER_BUILDKIT: '1'
    SKAFFOLD_DEFAULT_REPO: ${{ inputs.default-repo }}
    SKAFFOLD_PROFILE: ${{ inputs.profile }}
    SKAFFOLD_TAG: ${{ inputs.tag }}
    SKAFFOLD_BUILD_IMAGE: ${{ inputs.build-image }}
    SKAFFOLD_SKIP_TESTS : ${{ inputs.skip-tests }}
