name: Skaffold
description: Downloads skaffold dependencies
inputs:
  skaffold-version:
    description: Skaffold version
    required: false
    default: 1.9.0
outputs: {}
runs:
  using: docker
  image: Dockerfile
