apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: github-actions-skaffold

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  artifacts:
    - image: skaffold

deploy:
  helm:
    releases:
      - name: skaffold
        chartPath: .
        remote: false
        setValues:
          image: skaffold

test:
  - image: skaffold
    structureTests: [container-structure-test.yaml]
