apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: github-action-skaffold
build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    useDockerCLI: false
    concurrency: 0
  artifacts:
    - image: hiberb/skaffold
deploy:
  helm:
    releases:
      - name: skaffold
        chartPath: .
        remote: false
        setValues:
          image: skaffold
test:
  - image: hiberb/skaffold
    structureTests: [container-structure-test.yaml]

