apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: github-action-skaffold

build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: false
    useBuildkit: true
    useDockerCLI: false
  artifacts:
    - image: skaffold

deploy:
  helm:
    releases:
      - name: skaffold
        chartPath: charts/skaffold
        artifactOverrides:
          image: skaffold
        setValues:
          service.type: NodePort

profiles:
  - name: ci
    activation:
      - env: CI=true
    build:
      local:
        concurrency: 0
        push: true
        useBuildkit: true
        useDockerCLI: false
    test:
      - image: skaffold
        structureTests: [structure-test.yaml]
