apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: github-action-skaffold

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    useDockerCLI: true
    concurrency: 0
    push: false
  artifacts:
    - image: skaffold

deploy:
  helm:
    releases:
      - name: skaffold
        wait: true
        chartPath: src/charts/skaffold
        artifactOverrides:
          image: skaffold
        setValues:
          wordpress.service.type: ClusterIP

test:
  - image: skaffold
    structureTests: [structure-test.yaml]

