apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: github-actions-skaffold

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: skaffold
      docker:
        cacheFrom: [hiberb/skaffold:latest]

deploy:
  helm:
    releases:
      - name: skaffold
        chartPath: .
        remote: false
        setValues:
          image: skaffold

test:
  - image: skaffold
    structureTests: [container-structure-test.yaml]

profiles:
  - name: ci
    activation:
      - env: CI=true
    build:
      local:
        push: true
