name: Skaffold Pipiline
on: [push]
jobs:
  build:
    name: Build & Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@1.0.0

      - name: Configure Docker env
        run: echo '::set-env name=MINIKUBE_IP::$(minikube ip)'

      - name: Run Skaffold CI
        uses: hiberbee/github-action-skaffold@master
        env:
          KUBERNETES_SERVICE_HOST: $MINIKUBE_IP
          KUBERNETES_SERVICE_PORT: 8443
        with:
          args: run

      - name: Test container structure
        uses: hiberbee/github-action-skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config structure-test.yaml --image library/skaffold
