name: Skaffold
on: [push]
jobs:
  run:
    name: Run full pipiline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@master

      - name: Add Helm stable repository
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run Skaffold CI
        uses: hiberbee/github-action-skaffold@master
        with:
          command: run

      - name: Check Wordpress service
        run: kubectl get services
