name: Skaffold
on: [push]
jobs:
  run:
    name: Run Pipiline
    runs-on: ubuntu-20.04
    steps:
      - name: Extract cache
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/cache
          key: ${{ runner.os }}-skaffold-1.13.0
          restore-keys: ${{ runner.os }}-skaffold-

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: hiberbee/github-action-minikube@master

      - name: Authenticate with Docker registry
        run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Helm repositories
        run: helm repo --repository-config=repositories.yaml update

      - name: Run Skaffold command
        uses: hiberbee/github-action-skaffold@master
        with:
          command: run
          skip-tests: true
          default-repo: docker.pkg.github.com/${{ github.repository }}

      - name: Check deployed service
        run: kubectl get services
