name: Skaffold
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hiberbee/actions.skaffold@master
        with:
          command: version
      - uses: hiberbee/actions.skaffold@master
        with:
          command: build
      - uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: hiberbee/actions
          push: true
          tags: latest
