name: Skaffold Pipiline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository sources
        uses: actions/checkout@v2

      - name: Get Skaffold version
        uses: hiberbee/actions.skaffold@master
        with:
          args: version

      - name: Build Skaffold artifacts
        uses: hiberbee/actions.skaffold@master
        with:
          args: build

      - name: Test container structure
        uses: hiberbee/actions.skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config container-structure-test.yaml --image skaffold

      - name: Push image to Docker registry
        uses: docker/build-push-action@master
        with:
          entrypoint: build
          registry: docker.pkg.github.com/hiberbee/actions
          username: ${{ github.actor }}
          password: ${{ secrets.docker_password }}
          repository: skaffold
          add_git_labels: true
          push: true
          tags: latest
