name: Skaffold
on: push
jobs:
  run:
    name: Pipiline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest

      - name: Setup Helm
        uses: hiberbee/github-action-helm@latest

      - name: Authenticate with Docker registry
        run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login harbor.k8s.hiberbee.net -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Run Skaffold command
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
          skip-tests: true
          default-repo: harbor.k8s.hiberbee.net/library

      - name: Get Helm releases
        run: helm list
