name: Skaffold Pipiline
on: [push]
jobs:
  build:
    name: Build & Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Authenticate with Docker credentials
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Skaffold artifacts
        uses: hiberbee/github-action-skaffold@master
        with:
          default-repo: hiberb
          args: build

      - name: Test container structure
        uses: hiberbee/github-action-skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config container-structure-test.yaml --image skaffold

      - name: Get Skaffold version
        uses: hiberbee/github-action-skaffold@master
        with:
          args: version
