on:
  push:
    paths:
      - dist/**
      - .github/workflows/skaffold.yml
jobs:
  pipiline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest

      - name: Setup Helm
        uses: hiberbee/github-action-helm@latest

      - name: Authenticate with Docker registry
        run: echo $DOCKER_PASSWORD | docker login harbor.k8s.hiberbee.net -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

      - name: Run Skaffold command
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: run
          default-repo: harbor.k8s.hiberbee.net/library

      - name: Get Helm releases
        run: helm list
