name: Skaffold Pipiline
on: [push]
jobs:
  build:
    name: Build & Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@1.0.0

      - name: Configure Docker env
        run: |
          eval $(minikube docker-env)
          minikube update-context
          kubectl cluster-info

      - name: Run Skaffold CI
        uses: hiberbee/github-action-skaffold@master
        with:
          args: run
          skip-tests: true

      - name: Test container structure
        uses: hiberbee/github-action-skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config structure-test.yaml --image library/skaffold
