name: Skaffold
on: [push]
jobs:
  run:
    name: Run Pipiline
    runs-on: ubuntu-latest
    steps:
      - name: Extract cache
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/cache
          key: ${{ runner.os }}-skaffold

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@master

      - name: Add Helm stable repository
        run: helm repo --repository-config=repositories.yaml update

      - name: Run Skaffold command
        uses: hiberbee/github-action-skaffold@master
        with:
          command: run
          default-repo: docker.pkg.github.com/${{ github.repository }}

      - name: Check deployed service
        run: kubectl get services
