name: Skaffold Pipiline
on: [push]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    name: Build & Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@master

      - name: Run Skaffold CI
        uses: hiberbee/github-action-skaffold@master
        with:
          args: run

      - name: Test container structure
        uses: hiberbee/github-action-skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config structure-test.yaml --image library/skaffold
