name: Skaffold
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hiberbee/actions.skaffold@master
        with:
          command: version
      - uses: hiberbee/actions.skaffold@master
        with:
          command: build
      - uses: docker/build-push-action@master
        with:
          registry: docker.pkg.github.com/hiberbee/actions
          username: ${{ github.actor }}
          password: ${{ secrets.docker_password }}
          repository: skaffold
          add_git_labels: true
          push: true
          tags: latest
