name: Skaffold
on: [push]
env:
  SKAFFOLD_DEFAULT_REPO: docker.pkg.github.com/hiberbee/actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hiberbee/actions.skaffold@master
        with:
          command: version
      - uses: hiberbee/actions.skaffold@master
        with:
          command: build
