name: Skaffold
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hiberbee/actions.skaffold@master
        with:
          command: version
      - uses: hiberbee/actions.skaffold@master
        with:
          entrypoint: docker
          args: login --username=${{ github.actor }} --password=${{ secrets.docker_password }}
      - uses: hiberbee/actions.skaffold@master
        with:
          command: build
