name: Skaffold Pipiline
on: [push]
env:
  DOCKER_REGISTRY: docker.pkg.github.com/hiberbee/actions
jobs:
  build:
    name: Build & Test Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository sources
        uses: actions/checkout@v2

      - name: Authenticate with Docker credentials
        uses: azure/docker-login@v1
        with:
          login-server: $DOCKER_REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.docker_password }}

      - name: Get Skaffold version
        uses: hiberbee/actions.skaffold@master
        with:
          args: version

      - name: Build Skaffold artifacts
        uses: hiberbee/actions.skaffold@master
        with:
          default-repo: $DOCKER_REGISTRY
          args: build

      - name: Test container structure
        uses: hiberbee/actions.skaffold@master
        with:
          entrypoint: container-structure-test
          args: test --config container-structure-test.yaml --image skaffold
