name: Skaffold
on: [push]
env:
  SKAFFOLD_DEFAULT_REPO: docker.pkg.github.com/hiberbee/actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hiberbee/actions.skaffold@master
        with:
          command: version
      - run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login $SKAFFOLD_DEFAULT_REPO --username ${{ github.actor }} --password-stdin
      - uses: hiberbee/actions.skaffold@master
        with:
          command: build
